/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.kapralovs.basics;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        Scanner in=new Scanner(System.in);
        System.out.print("Input a number: ");
        int num=in.nextInt();

        System.out.printf("Your number: %d\n",num);
        in.close();
    }
}
